language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -qq

install:
    - pip install -r python-requirements.txt --use-mirrors
script:
    - ./validate.sh
    - python -m unittest -v updatechangelog.tests
